-- MySQL Script generated by MySQL Workbench
-- 11/29/17 09:27:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vanelles
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vanelles
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vanelles` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `vanelles` ;

-- -----------------------------------------------------
-- Table `vanelles`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vanelles`.`role` (
  `role` INT NOT NULL DEFAULT 2 COMMENT '',
  `role_name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`role`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanelles`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vanelles`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `first_name` VARCHAR(45) NULL COMMENT '',
  `insertion` VARCHAR(45) NULL COMMENT '',
  `last_name` VARCHAR(45) NULL COMMENT '',
  `phonenumber` INT(12) NULL COMMENT '',
  `city` VARCHAR(45) NULL COMMENT '',
  `address` VARCHAR(45) NULL COMMENT '',
  `zipcode` VARCHAR(45) NULL COMMENT '',
  `role` INT NOT NULL DEFAULT 2 COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '',
  INDEX `fk_user_role_idx` (`role` ASC)  COMMENT '',
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`role`)
    REFERENCES `vanelles`.`role` (`role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanelles`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vanelles`.`admin` (
  `user_id` INT NOT NULL COMMENT '',
  `gebruikersnaam` VARCHAR(45) NOT NULL COMMENT '',
  `wachtwoord` CHAR(128) NOT NULL COMMENT '',
  `salt` VARCHAR(45) NOT NULL COMMENT '',
  `hash` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '',
  INDEX `fk_admin_user1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_admin_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `vanelles`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanelles`.`blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vanelles`.`blog` (
  `blog_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  `title` VARCHAR(45) NOT NULL COMMENT '',
  `subtitle` VARCHAR(45) NOT NULL COMMENT '',
  `inhoud` VARCHAR(45) NOT NULL COMMENT '',
  `datum` TIMESTAMP(20) NOT NULL COMMENT '',
  `beschijving` VARCHAR(2000) NOT NULL COMMENT '',
  `kernwoorden` VARCHAR(45) NOT NULL COMMENT '',
  `img_name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`blog_id`)  COMMENT '',
  INDEX `fk_blog_admin1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_blog_admin1`
    FOREIGN KEY (`user_id`)
    REFERENCES `vanelles`.`admin` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanelles`.`activiteit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vanelles`.`activiteit` (
  `activiteit_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `inschijvingen` INT(2) NOT NULL COMMENT '',
  `max` INT(2) NOT NULL COMMENT '',
  `datum` DATE NOT NULL COMMENT '',
  `blog_blog_id` INT NULL COMMENT '',
  PRIMARY KEY (`activiteit_id`)  COMMENT '',
  INDEX `fk_activiteit_blog1_idx` (`blog_blog_id` ASC)  COMMENT '',
  CONSTRAINT `fk_activiteit_blog1`
    FOREIGN KEY (`blog_blog_id`)
    REFERENCES `vanelles`.`blog` (`blog_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanelles`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vanelles`.`contact` (
  `contact_id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `date` TIMESTAMP(6) NOT NULL COMMENT '',
  `inhoud` VARCHAR(2000) NOT NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  `datum` TIMESTAMP(20) NOT NULL COMMENT '',
  PRIMARY KEY (`contact_id`)  COMMENT '',
  INDEX `fk_contact_user1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_contact_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `vanelles`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanelles`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vanelles`.`review` (
  `review_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `quote` VARCHAR(200) NOT NULL COMMENT '',
  `rating` INT(1) NOT NULL COMMENT '',
  `naam` VARCHAR(45) NOT NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  `datum` DATETIME(20) NOT NULL COMMENT '',
  PRIMARY KEY (`review_id`)  COMMENT '',
  INDEX `fk_review_user1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_review_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `vanelles`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanelles`.`leveranciers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vanelles`.`leveranciers` (
  `lev_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `naam` VARCHAR(45) NULL COMMENT '',
  `inhoud` VARCHAR(45) NULL COMMENT '',
  `logo` VARCHAR(45) NULL COMMENT '',
  `description` VARCHAR(45) NULL COMMENT '',
  `kernwoorden` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`lev_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanelles`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vanelles`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `naam` VARCHAR(45) NOT NULL COMMENT '',
  `inhoud` VARCHAR(45) NOT NULL COMMENT '',
  `images` VARCHAR(45) NOT NULL COMMENT '',
  `description` VARCHAR(45) NOT NULL COMMENT '',
  `kernwoorden` VARCHAR(45) NOT NULL COMMENT '',
  `lev_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`product_id`)  COMMENT '',
  INDEX `fk_product_leveranciers1_idx` (`lev_id` ASC)  COMMENT '',
  CONSTRAINT `fk_product_leveranciers1`
    FOREIGN KEY (`lev_id`)
    REFERENCES `vanelles`.`leveranciers` (`lev_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanelles`.`inschijvingen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vanelles`.`inschijvingen` (
  `inschijving_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `activiteit_id` INT NOT NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`inschijving_id`)  COMMENT '',
  INDEX `fk_inschijvingen_activiteit1_idx` (`activiteit_id` ASC)  COMMENT '',
  INDEX `fk_inschijvingen_user1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_inschijvingen_activiteit1`
    FOREIGN KEY (`activiteit_id`)
    REFERENCES `vanelles`.`activiteit` (`activiteit_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inschijvingen_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `vanelles`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanelles`.`Module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vanelles`.`Module` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `naam` VARCHAR(45) NOT NULL COMMENT '',
  `path` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vanelles`.`page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vanelles`.`page` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(100) NULL COMMENT '',
  `subtitle` VARCHAR(100) NULL COMMENT '',
  `inhoud` VARCHAR(2000) NULL COMMENT '',
  `description` VARCHAR(2000) NULL COMMENT '',
  `kernwoorden` VARCHAR(100) NULL COMMENT '',
  `active` VARCHAR(45) NULL COMMENT '',
  `datum` DATE NULL COMMENT '',
  `image` VARCHAR(45) NULL COMMENT '',
  `Module_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_page_Module1_idx` (`Module_id` ASC)  COMMENT '',
  CONSTRAINT `fk_page_Module1`
    FOREIGN KEY (`Module_id`)
    REFERENCES `vanelles`.`Module` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
